config/routes.rb
Rails.application.routes.draw do
  # Devise routes for user authentication
  devise_for :users

  # Resourceful routes for Balances and nested Items
  resources :balances, only: [:index, :show, :new, :create] do
    resources :items, only: [:new, :create]
  end

  # Root route
  root 'balances#index'

  # Custom route for the home page
  get '/home', to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :balance_items, dependent: :destroy
  has_many :items, through: :balance_items, dependent: :destroy, source: 'item'

  validates :name, :icon, presence: true
end

app/models/balance_item.rb
class BalanceItem < ApplicationRecord
  belongs_to :item
  belongs_to :balance
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :balance_items, dependent: :destroy
  has_many :balances, through: :balance_items, dependent: :destroy, source: 'balance'

  validates :name, :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy, foreign_key: :author_id
  has_many :balances, dependent: :destroy, foreign_key: :author_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_balance, only: [:show]

  def index
    @balances = current_user.balances.includes(:items).order(created_at: :desc)
  end

  def new
    @balance = Balance.new
  end

  def show
    if current_user.id == @balance.author_id
      # You can remove the redundant Balance.find since @balance is already loaded
    else
      redirect_to '/', alert: 'You do not have permission to access this balance.'
    end
  end

  def create
    @balance = current_user.balances.build(balance_params)
    if @balance.save
      redirect_to root_path, notice: 'Balance is successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to home_path
    end
  end

  def balance_params
    params.require(:balance).permit(:name, :icon)
  end

  def load_balance
    @balance = Balance.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless current_user

    redirect_to '/'
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_balance, only: %i[new create]

  def new
    if current_user.id == @balance.author_id
      @item = Item.new
      @balances = Balance.where(author_id: current_user.id)
    else
      redirect_to '/'
    end
  end

  def create
    @item = Item.new(name: params[:item][:name], amount: params[:item][:amount], author_id: current_user.id)
    if params[:item][:selected_ids].present?
      if save_and_balance_item
        redirect_to balance_path(params[:balance_id])
      else
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to balance_items_path(params[:balance_id]), alert: 'Check at least one checkbox!'
    end
  end

  private

  def save_and_balance_item
    ActiveRecord::Base.transaction do
      @item.save
      params[:item][:selected_ids].each do |id|
        BalanceItem.create(item_id: @item.id, balance_id: id.to_i)
      end
    end
  rescue ActiveRecord::RecordInvalid
    false
  end

  def item_params
    params.require(:item).permit(:name, :amount, selected_ids: [])
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to home_path
    end
  end

  def load_balance
    @balance = Balance.find(params[:balance_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/balances/index.html.erb
<%= stylesheet_link_tag "balances_styles", media: "all", "data-turbolinks-track": "reload" %>

<div class="balance-sheet-index">
    <div class="bg-header-balance">
          <svg id="hamburger" viewBox="0 0 100 80" width="40" height="40" fill="white">
            <rect width="100" height="10"></rect>
            <rect y="30" width="100" height="10"></rect>
            <rect y="60" width="100" height="10"></rect>
          </svg>
          <h1 class="balance-header">BALANCE SHEET</h1>
          <svg id="src-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
            <circle cx="11" cy="11" r="8"/>
            <line x1="21" x2="16.65" y1="21" y2="16.65"/>
          </svg>
    </div>


  <ul class="w-screen p-3">
    <% @balances.each do |balance| %>
      <%= link_to "/balances/#{balance.id}" do %>
        <li class="balance-item">
          <img class="balance-icon" src=<%= balance.icon %> alt=<%= balance.name %> >
          <div class="balance-details">
            <p class="balance-name"><%= balance.name.capitalize %></p>
            <p class="balance-date"><%= balance.created_at.strftime('%d-%b-%Y') %></p>
          </div>
          <p class="balance-amount">$<%= balance.items.map { |item| item.amount }.sum %></p>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="add-button">
  <%= link_to "+", new_balance_path, class: "add-button-link" %>
</div>

app/views/balances/new.html.erb
<%= stylesheet_link_tag "new_balance_styles", media: "all", "data-turbolinks-track": "reload" %>


<div class="balance-sheet-index">
  <div class="bg-header">
      <%= link_to '<', root_path, class: "back-btn" %>
      <h1 class="text-header">NEW BALANCE SHEET</h1>
  </div>

  <% if @balance.errors.any? %>
    <div class="error-message">
      <p><%= pluralize(@balance.errors.count, "error") %> found:</p>

      <ul>
        <% @balance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @balance, url: balances_path, method: :post, class: "form-container" do |form| %>
    <div class="input-field">
      <%= form.text_field :name, placeholder: 'Name', required: true %>
    </div>

    <div class="input-field">
      <%= form.text_field :icon, placeholder: 'icon URL', required: true %>
    </div>

    <div class="actions">
      <%= form.submit 'Save' %>
    </div>
    <% end %>
</div>

app/views/balances/show.html.erb
<%= stylesheet_link_tag "balance_details", media: "all", "data-turbolinks-track": "reload" %>


<div class="balance-sheet-index">
    <div class="bg-header">
      <%= link_to '<', root_path, class: "bb-btn" %>
      <h1 class="text-header">DETAILS</h1>
    </div>
  <div class="details-container">
    <div class="item-container">
      <div class="item-header">
        <img class="item-icon" src=<%= @balance.icon %> alt=<%= @balance.name%> >
        <p class="item-name"><%= @balance.name.capitalize%></p>
      </div>
      <% total = 0 %>
      <% @balance.items.each do |item| %>
        <div class="flex flex-col">
          <div class="flex justify-between">
            <p class="pt-3 text-bold text-2xl"><%= item.name %></p>
            <p class="pt-3 text-bold text-xl">$<%= item.amount %></p>
          </div>
          <p class="text-gray-400 text-sm"><%= item.created_at.strftime('%d-%b-%Y') %></p>
        </div>
        <% total += item.amount %>
      <% end %>
      <div class="total-payment">
        <p>TOTAL PAYMENT</p>
        <p>$<%= total %></p>
      </div>
    </div>
  </div>
</div>

<div class="fab">
  <%= link_to '+', new_balance_item_path(@balance.id), class: "fab-icon" %>
</div>

app/views/home/index.html.erb
<%= stylesheet_link_tag "home_styles", media: "all", "data-turbolinks-track": "reload" %>

<div class="home-container">
  <div class="home-heading">House Budget App</div>
  <%# <div></div> %>
  <div class="home-buttons">
    <%= link_to "LOG IN", new_user_session_path, class: "home-login-button" %>
    <%= link_to "SIGN UP", new_user_registration_path, class: "home-signup-button" %>
  </div>
</div>

app/views/items/new.html.erb
<%= stylesheet_link_tag "custom_item_styles", media: "all", "data-turbolinks-track": "reload" %>

<div>
  <div class="bg-header">
    <%= link_to root_path, class: "header-link" do %>
        <h1 class="text-3xl">New Item</h1>
    <% end %>
  </div>

  <% if @item.errors.any? %>
    <div class="error-message">
      <p><%= pluralize(@item.errors.count, "error") %> Found:</p>
      <ul class="font-bold">
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @item, url: balance_items_path, method: :post, class: "item-form" do |form| %>
    <div class="form-fields">
      <%= form.text_field :name, placeholder: 'Name', required: true %>
      <%= form.number_field :amount, placeholder: 'Amount', required: true %>

      <div class="balance-chooser">
        <p class="font-bold">Choose Balance Sheet to Add this item</p>
        <div class="balance-options">
          <% @balances.each do |balance| %>
            <% checked = balance.id.to_i == params[:balance_id].to_i ? { checked: true } : {} %>
            <div class="balance-option">
              <%= form.check_box :selected_ids, { multiple: true }.merge(checked), balance.id, nil %>
              <%= label_tag "balance_#{balance.id}", balance.name %>
            </div>
          <% end %>
        </div>
      </div>
      <span class="submit-button">
        <%= form.submit "Save Item" %>
      </span>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="nav-container">
      <div class="atert-msg">
        <p><%= notice %></p>
        <p><%= alert %></p>
      </div>
      <% if user_signed_in? %>
          <%= button_to "Log out", '/users/sign_out', method: :delete, data: { turbo: false }, class: "logout-btn" %>
      <% end %>
    </main>
    <%= yield %>
</body>

</html>